services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project-timesheet-backend  
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      APP_NAME: project-timesheet-backend
      APP_VERSION: 1.0.0
      HTTP_PORT: 8080
      MYSQL_URL: project_timesheet_admin:P@ssw0rd@tcp(mysql:3306)/project_timesheet?charset=utf8&parseTime=True&loc=Asia%2FBangkok
      LOG_LEVEL: debug
      TOKEN_SYMMETRIC: Ik0clmMdcUCeuBLOuvq9dtSIrQYV5RvE
      ACCESS_TOKEN_DURATION: 2h
      REFRESH_TOKEN_DURATION: 24h
    networks:
      - project-timesheet

  mysql:
    container_name:  project-timesheet-db
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: project_timesheet
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_USER: project_timesheet_admin
      MYSQL_ROOT_PASSWORD: r00t@1234
    ports:
      - 3306:3306
    volumes:
      - ./pkg/mysql/1-init-grant.sql:/docker-entrypoint-initdb.d/1-init-grant.sql
      - ./pkg/mysql/2-init-roles.sql:/docker-entrypoint-initdb.d/2-init-roles.sql
      - ./pkg/mysql/3-init-users.sql:/docker-entrypoint-initdb.d/3-init-users.sql
      - ./pkg/mysql/4-init-projects.sql:/docker-entrypoint-initdb.d/4-init-projects.sql
      - ./pkg/mysql/5-init-worktypes.sql:/docker-entrypoint-initdb.d/5-init-worktypes.sql
      - ./pkg/mysql/6-init-duties.sql:/docker-entrypoint-initdb.d/6-init-duties.sql
      - ./pkg/mysql/7-init-statuses.sql:/docker-entrypoint-initdb.d/7-init-statuses.sql
      - ./pkg/mysql/8-init-time-entries.sql:/docker-entrypoint-initdb.d/8-init-time-entries.sql
    networks:
      - project-timesheet

  adminer:
    container_name:  project-timesheet-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - project-timesheet

networks:
  project-timesheet:
    name: project-timesheet
    driver: bridge

