app:
  name: 'project-timesheet-backend'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'

mysql:
  url: project_timesheet_admin:P@ssw0rd@tcp(127.0.0.1:3306)/project_timesheet?charset=utf8&parseTime=True&loc=Asia%2FBangkok